name: Deploy App to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.403

      - name: Publish .NET Core Project
        run: dotnet publish ArkNovaCompanion.csproj -c Release -o release --nologo

      - name: Set subdirectory
        run: echo "SUBDIRECTORY='ArkNovaCompanion'" >> $GITHUB_ENV

      - name: Update base href
        run: sed -i "s|<base href=\"/\">|<base href=\"/$SUBDIRECTORY/\">|" index.html

      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll

      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: master
          folder: release/wwwroot
